spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      first:  #数据源1
        url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
        username: root
        password: tiger
  data:
    jpa:
      repositories:
        enabled: true
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 47.101.189.129:9300
      repositories:
        enabled: true
    redis:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
#    database: MYSQL
  freemarker:
    template-loader-path: classpath:/statics/ref
    request-context-attribute: request
    suffix: .html
    content-type: text/html
    enabled: true
    charset: UTF-8
    settings:
      number_format: '0.##'
  main:
    banner-mode: console
  redis:
    database: 0
    host: 47.101.189.129
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  rabbitmq:
    host: 47.101.189.129
    port: 5672
    username: guest
    password: guest
    virtual-host: /
#  profiles:
#    active: dev
#mybatis:
#  config-location: conf/mybatis-config.xml
#  mapper-locations: classpath:conf/mapper/*.xml
#  type-aliases-package: com.crawler.crawler.model
server:
  port: 80
  servlet:
    context-path: /perplayer
  tomcat:
    uri-encoding: UTF-8
crawler:
  cluster: false
  globalSessionTimeout: 3600

management:
  endpoints:
    web:
      exposure:
        include: env, beans, info, configprops
