spring:
  datasource:
    password: tiger
    username: scott
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#mybatis:
#  config-location: conf/mybatis-config.xml
#  mapper-locations: classpath:conf/mapper/*.xml
#  type-aliases-package: com.crawler.crawler.model
