spring:
  datasource:
#    url: jdbc:mysql://47.101.189.129:3307/test?characterEncoding=UTF-8
#    username: root
#    password: tiger
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      first:  #数据源1
        url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
        username: scott
        password: tiger
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
#    database: MYSQL
  freemarker:
    template-loader-path: classpath:/statics/ref
    request-context-attribute: request
    suffix: .html
    content-type: text/html
    enabled: true
    charset: UTF-8
    settings:
      number_format: '0.##'
#  profiles:
#    active: dev
#mybatis:
#  config-location: conf/mybatis-config.xml
#  mapper-locations: classpath:conf/mapper/*.xml
#  type-aliases-package: com.crawler.crawler.model
server:
  port: 80
  servlet:
    context-path: /perplayer
  tomcat:
    uri-encoding: UTF-8
