spring:
  datasource:
    username: root
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.189.129:3307/test
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
#    database: MYSQL

#  profiles:
#    active: dev
#mybatis:
#  config-location: conf/mybatis-config.xml
#  mapper-locations: classpath:conf/mapper/*.xml
#  type-aliases-package: com.crawler.crawler.model
server:
  port: 80
  servlet:
    context-path: /perplayer
  tomcat:
    uri-encoding: UTF-8
